import { type NextPage } from "next";
import Image from "next/image";
import Head from "next/head";
import { SignIn, SignInButton, useUser, SignOutButton } from "@clerk/nextjs";
import { LoadingPage, LoadingSpinner } from "~/components/loading";

const ProfilePage: NextPage = () => {
  return (
    <>
      <Head>
        <title>lacht</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-auto justify-center  ">
        <div className="w-full border-x border-slate-200 md:max-w-2xl">
          Test Perfil
        </div>

        <SignIn path="/sign-in" routing="path" signUpUrl="/sign-up" />
      </main>
    </>
  );
};

export default ProfilePage;
