import { type NextPage } from "next";
import Image from "next/image";
import Head from "next/head";
import { SignIn, SignInButton, useUser, SignOutButton } from "@clerk/nextjs";
import { RouterOutputs, api } from "~/utils/api";
import { LoadingPage, LoadingSpinner } from "~/components/loading";
import { useState } from "react";
import toast from "react-hot-toast";
const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>lacht</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-auto justify-center  ">
        Soy un post!
        <SignIn path="/sign-in" routing="path" signUpUrl="/sign-up" />
      </main>
    </>
  );
};

export default Home;
